### ISSUE TITLE
🚧Create org level bug template

### ISSUE THREAD

**Issue by kselena** [niceplaces/.github#1]
If someone finds a bug in any of the repos, it would be best for the organization to hold the bug template so that each repo can use them and to keep it consistent throughout the organization.  This also means that any templates at the repo level should be deleted. 

Here's an example of the information in the bug template: 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/96791049/211553783-f8446652-5950-44ec-87ac-3e31fb27dc12.png">

Here's an example of a more descriptive bug template: 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/96791049/211554372-1fe642a5-01b1-4dbe-b8eb-9de9f99a4360.png">

**Comment by lorenzovngl** [comment]
I like the detailed version, could you proceed to add it?
