### ISSUE TITLE
🚧Create org level feature template 

### ISSUE THREAD

**Issue by kselena** [niceplaces/.github#2]
If someone wants to add a feature into any of the repos, it would be best for the organization to hold all of the templates so that each repo can use them and to keep it consistent throughout the organization.  This also means that any templates at the repo level should be deleted. 

Here's an idea of the information in the feature template: 
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/96791049/211553486-6db54223-6ed8-4d77-ba8d-b8649b1a792a.png">

Here's another example of a more descriptive feature template: 
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/96791049/211554557-f900db5e-1c2b-4374-b510-159b2d044df6.png">

**Comment by lorenzovngl** [comment]
I like the detailed version, could you proceed to add it?

**Comment by kselena** [comment]
@lorenzovngl Do you want any changes to either of them or do you like them the way they are?
